package com.inbound_service.dto.response;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record RmaResponse(
    UUID id,
    String rmaNumber,
    String returnType,
    UUID salesOrderId,
    UUID supplierId,
    String supplierName,
    UUID customerId,
    String customerName,
    String status,
    String reason,
    UUID warehouseId,
    String warehouseName,
    OffsetDateTime createdAt,
    OffsetDateTime receivedAt,
    OffsetDateTime completedAt,
    UUID createdBy,
    UUID receivedBy,
    UUID completedBy,
    UUID approvedBy,
    OffsetDateTime approvedAt,
    UUID rejectedBy,
    OffsetDateTime rejectedAt,
    String rejectionReason,
    UUID cancelledBy,
    OffsetDateTime cancelledAt,
    String cancelReason,
    Integer totalExpectedQty,
    Integer totalReceivedQty,
    Integer totalRemainingQty,
    List<ItemResponse> items
) {
    public record ItemResponse(
        UUID id,
        UUID productId,
        UUID salesOrderItemId,
        String productName,
        String productSku,
        Integer expectedQty,
        Integer receivedQty,
        Integer remainingQty,
        UUID receivedLocationId,
        String receivedLocationCode,
        UUID returnLocationId,
        String returnLocationCode,
        String lotNumber,
        String condition,
        String dispositionAction,
        UUID dispositionLocationId,
        String dispositionLocationCode,
        OffsetDateTime dispositionAt,
        UUID dispositionBy,
        String dispositionNote,
        UUID supplierReturnRmaId,
        String notes
    ) {}
}
