package com.ai_service.intent;

public enum AiIntent {
    WAREHOUSE_COUNT,
    WAREHOUSE_LIST,
    WAREHOUSE_DETAIL,
    LOCATION_SEARCH,
    STOCK_BY_PRODUCT,
    STOCK_TOTAL,
    STOCK_LOWEST,
    WAREHOUSE_STOCK_SUMMARY,
    LOW_STOCK,
    NEAR_EXPIRY,
    PENDING_PUTAWAY,
    LATEST_INBOUND,
    PURCHASE_ORDER_STATUS,
    OUTBOUND_PRIORITY,
    PICKING_STATUS,
    ACTIVE_CYCLE_COUNTS,
    CYCLE_COUNT_VARIANCE,
    RMA_PENDING,
    DAILY_TASKS,
    REPORT_SUMMARY,
    GENERAL_GUIDE,
    AMBIGUOUS,
    UNSUPPORTED
}
