package com.ai_service.intent;

// Tổng số nhãn intent hiện tại: 62.
public enum AiIntent {
    // Kho hàng & Vị trí
    WAREHOUSE_COUNT, WAREHOUSE_LIST, WAREHOUSE_DETAIL,
    LOCATION_SEARCH, LOCATION_COUNT, BEST_HEAVY_LOCATION,

    // Sản phẩm & Nhà cung cấp & Khách hàng
    PRODUCT_COUNT, PRODUCT_LIST, PRODUCT_DETAIL,
    SUPPLIER_LIST, SUPPLIER_SEARCH, SUPPLIER_DETAIL,
    CUSTOMER_LIST, CUSTOMER_SEARCH, CUSTOMER_DETAIL,
    SUPPLIER_TOP,

    // Tồn kho
    STOCK_BY_PRODUCT, STOCK_TOTAL, STOCK_LOWEST, STOCK_HIGHEST,
    PRODUCT_BY_BARCODE, LOT_TRACKED_COUNT, STOCK_BELOW_THRESHOLD,
    WAREHOUSE_STOCK_SUMMARY, LOW_STOCK, NEAR_EXPIRY,
    STOCK_MOVEMENT_HISTORY, STOCK_TRANSFER, INVENTORY_ADJUSTMENT, INVENTORY_VALUE,
    SLOW_MOVING_STOCK,

    // Nhập kho
    PENDING_PUTAWAY, PUTAWAY_BY_WAREHOUSE, INBOUND_TODAY,
    LATEST_INBOUND, PENDING_PO_RECEIPT, PURCHASE_ORDER_STATUS,
    PURCHASE_ORDER_DETAIL, PURCHASE_ORDER_APPROVAL_AUDIT,
    INBOUND_RECEIPT_STATUS, INBOUND_RECEIPT_DETAIL,

    // Xuất kho & Bán hàng
    OUTBOUND_PRIORITY, PACKING_STATUS, PICKING_TOP, PICKING_STATUS,
    SALES_TOP, SALES_ORDER_DETAIL, SALES_ORDER_STATUS, FLOW_REPORT,

    // Kiểm kê
    ACTIVE_CYCLE_COUNTS, CYCLE_COUNT_VARIANCE, CYCLE_COUNT_STATUS,

    // RMA
    RMA_PENDING,

    // Báo cáo & Thống kê
    REPORT_SUMMARY, DAILY_TASKS, INBOUND_REPORT, OUTBOUND_REPORT,
    MONTHLY_REPORT, MONTH_OVER_MONTH_FLOW,

    // Hỗ trợ & Khác
    GENERAL_GUIDE, GLOBAL_SEARCH, AUDIT_LOG, AI_AUDIT_LOG, USER_PERMISSION,
    AMBIGUOUS, UNSUPPORTED
}
