package com.ai_service.intent;

public enum AiIntent {
    WAREHOUSE_COUNT,
    WAREHOUSE_LIST,
    WAREHOUSE_DETAIL,
    LOCATION_SEARCH,
    STOCK_BY_PRODUCT,
    LOW_STOCK,
    NEAR_EXPIRY,
    PENDING_PUTAWAY,
    PURCHASE_ORDER_STATUS,
    OUTBOUND_PRIORITY,
    PICKING_STATUS,
    CYCLE_COUNT_VARIANCE,
    REPORT_SUMMARY,
    GENERAL_GUIDE,
    AMBIGUOUS,
    UNSUPPORTED
}
