ALTER TABLE products
    ADD COLUMN is_frozen  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN is_fragile BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN is_hazmat  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN is_heavy   BOOLEAN NOT NULL DEFAULT FALSE;
