ALTER TABLE locations
    ADD COLUMN IF NOT EXISTS is_cold_zone BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_hazmat_zone BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_heavy_zone BOOLEAN NOT NULL DEFAULT FALSE;
