INSERT INTO audit_logs (
    id,
    service_name,
    module,
    action_type,
    action,
    entity_type,
    entity_id,
    entity_name,
    actor_id,
    actor_name,
    actor_email,
    reason,
    before_snapshot,
    after_snapshot,
    metadata,
    ip_address,
    user_agent,
    created_at
) VALUES (
    '22222222-2222-2222-2222-222222222201',
    'warehouse-app',
    'STOCK',
    'ADJUST',
    'Adjust stock level',
    'StockLevel',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
    'CTN-A4 at WH-HCM-A01',
    '99999999-9999-9999-9999-999999999903',
    'Le Van Kho',
    'staff@warehouse.local',
    'Kiem ke phat hien lech ton thuc te',
    '{"quantityOnHand":500,"availableQuantity":480}',
    '{"quantityOnHand":492,"availableQuantity":472}',
    '{"source":"seed","adjustmentType":"COUNT_CORRECTION"}',
    '127.0.0.1',
    'Mozilla/5.0 Demo Browser',
    NOW() - INTERVAL '3 days'
)
ON CONFLICT (id) DO NOTHING;
