INSERT INTO audit_logs (
    id,
    service_name,
    module,
    action_type,
    action,
    entity_type,
    entity_id,
    entity_name,
    actor_id,
    actor_name,
    actor_email,
    reason,
    before_snapshot,
    after_snapshot,
    metadata,
    ip_address,
    user_agent,
    created_at
) VALUES (
    '33333333-3333-3333-3333-333333333301',
    'warehouse-app',
    'INBOUND',
    'APPROVE',
    'Approve purchase order',
    'PurchaseOrder',
    'cccccccc-cccc-cccc-cccc-ccccccccccc1',
    'PO-2026-0001',
    '99999999-9999-9999-9999-999999999902',
    'Tran Thi Manager',
    'manager@warehouse.local',
    'Duyet don nhap hang thang 04',
    '{"status":"DRAFT","totalItems":3}',
    '{"status":"APPROVED","totalItems":3}',
    '{"source":"seed","approvalLevel":"MANAGER"}',
    '127.0.0.1',
    'Mozilla/5.0 Demo Browser',
    NOW() - INTERVAL '2 days'
)
ON CONFLICT (id) DO NOTHING;
