INSERT INTO audit_logs (
    id,
    service_name,
    module,
    action_type,
    action,
    entity_type,
    entity_id,
    entity_name,
    actor_id,
    actor_name,
    actor_email,
    reason,
    before_snapshot,
    after_snapshot,
    metadata,
    ip_address,
    user_agent,
    created_at
) VALUES (
    '44444444-4444-4444-4444-444444444401',
    'warehouse-app',
    'OUTBOUND',
    'PICK',
    'Pick sales order item',
    'PickingItem',
    'dddddddd-dddd-dddd-dddd-ddddddddddd1',
    'SO-2026-0001 / CTN-A4',
    '99999999-9999-9999-9999-999999999903',
    'Le Van Kho',
    'staff@warehouse.local',
    'Pick hang theo don xuat da xac nhan',
    '{"status":"ASSIGNED","pickedQuantity":0}',
    '{"status":"PICKED","pickedQuantity":20}',
    '{"source":"seed","locationCode":"WH-HCM-A01"}',
    '127.0.0.1',
    'Mozilla/5.0 Demo Browser',
    NOW() - INTERVAL '1 day'
)
ON CONFLICT (id) DO NOTHING;
