package com.common.notification;

public enum NotificationType {
    LOW_STOCK,
    PURCHASE_ORDER_CREATED,
    RMA_RECEIVED,
    PICKING_ASSIGNED,
    PICKING_EXCEPTION,
    CYCLE_COUNT_CREATED,
    CYCLE_COUNT_ASSIGNED,
    CYCLE_COUNT_SUBMITTED,
    CYCLE_COUNT_APPROVED,
    CYCLE_COUNT_REJECTED,
    STOCK_DISCREPANCY,
    ROLE_CHANGED,
    SYSTEM_ALERT
}
